package com.delight.demo.entity;



import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Student")
public class Student implements Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@DynamoDBHashKey  (attributeName = "studentId")
    @DynamoDBAutoGeneratedKey
    private String studentId;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private int mobileNumber;
    @DynamoDBAttribute
    private String email;
}
